---
before_script:
  - gem install slim
  - npm install
language: javascript
env:
  global:
    - GITHUB_REPO: "ntt-developers/ntt-tech-conference-01"
    - secure: "lh9pTGbKf7Yn3O+YLZGo3yaTtKyd48FlpbEiFL55UvLSU1flehvkTf70NLpPvMNzkXCzf+psMSiGmCQIeJCBipqh1e7QIczqkyS8N4P+g3BjlNpNSYl5vDxgdoyeekt6xDPumYvlYQyzYpEZX7qBiluoOI4g0SQX/PorR/rsXQbAX4H+woYW93RwUGltzk8EtasZBjKmtCHuW/Q8p8poy56VQxd7SxaLa/npQH2SCoWxtvaXZJkEp8US5vAPkyCLhQHEcHbrPjBxiINjz/pld1KUkl9dzq1EmdwlAwGsgSnpRIXBMXAYMJ3A2iVIXBxwS+s6etiBRJI+t8v0PHo0Yp5oVurXxzOlR/ThOiIdFQmVufxl7LGGP8xZ5Np99qmK7X2vk0oi4Wg1Ib41fQSLWOP2KjZc1QQ8TKO2TDDlRGGrZtJIHHR1JM48maeOxyv4qqCtyDU6uyd9mMZw1BRrz6KodSvh9iqHtj+5Ih6rInITrAim6WcLE3e4lq6Z67XNLBgYPHZ2YxffSj4YJN2zIYg2RcAq41fDQ+A8Y+40kJiXsga9H3EwGBTlM6Yl2uC7FhEaODL8bQ/71pUnV7FPVg+wNLvODnoFkxTXaLWvRxju4n/Sl8Bkehfdqb4eHVSgllruj1LJIw6OSGEtdw3QGhstKKWbvC2YlYOS4CHuOHY="
script:
  - mv index.html diff-index.html
  - mv for-beginners.html diff-for-beginners.html
  - mv conference.html diff-conference.html
  - mv unconference.html diff-unconference.html
  - mv timetable.html diff-timetable.html
  - mv showcase.html diff-showcase.html
  - npm run build
  - diff index.html diff-index.html
  - diff for-beginners.html diff-for-beginners.html
  - diff conference.html diff-conference.html
  - diff unconference.html diff-unconference.html
  - diff timetable.html diff-timetable.html
  - diff showcase.html diff-showcase.html
cache:
  directories:
    - node_modules
    - bower_components
after_success:
  - |
       declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
       openssl aes-256-cbc \
         -K $encrypted_30975c018d00_key \
         -iv $encrypted_30975c018d00_iv \
         -in ".travis/github_deploy_key.enc" \
         -out "$SSH_FILE" -d

       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config

       ./deploy.sh
